/**
 * projectInfoDoc.java
 *
 * This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.projectInfo;

public class projectInfoDoc extends com.altova.xml.Document {
	public void declareNamespaces(com.altova.xml.Node node) {
	}
}
