/**
 * SchemaNormalizedString.java
 *
 * This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package com.altova.types;

public class SchemaNormalizedString extends SchemaString {
	public SchemaNormalizedString() {
		super();
	}

	public SchemaNormalizedString(String newvalue) {
		super(newvalue);
	}

	public SchemaNormalizedString(SchemaNormalizedString newvalue) {
		super((SchemaString)newvalue);
	}
}
