/**
 * SchemaTypeException.java
 *
 * This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.altova.types;


public class SchemaTypeException extends com.altova.AltovaException {
	public SchemaTypeException(String text) {
		super(text);
	}

	public SchemaTypeException(Exception other) {
		super(other);
	}
}
