/**
 * SchemaToken.java
 *
 * This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package com.altova.types;

public class SchemaToken extends SchemaNormalizedString {
	public SchemaToken() {
		super();
	}

	public SchemaToken(String newvalue) {
		super(newvalue);
	}

	public SchemaToken(SchemaToken newvalue) {
		super((SchemaNormalizedString)newvalue);
	}
}
