/**
 * BasicFactorType.java
 *
 * This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.FFT;

import com.altova.types.SchemaDouble;
import com.altova.types.SchemaString;

public class BasicFactorType extends com.altova.xml.Node {

	public BasicFactorType(BasicFactorType node) {
		super(node);
	}

	public BasicFactorType(org.w3c.dom.Node node) {
		super(node);
	}

	public BasicFactorType(org.w3c.dom.Document doc) {
		super(doc);
	}

	public BasicFactorType(com.altova.xml.Document doc, String namespaceURI, String prefix, String name) {
		super(doc, namespaceURI, prefix, name);
	}
	
	public void adjustPrefix() {
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Attribute, null, "Name" );
				tmpNode != null;
				tmpNode = getDomNextChild( Attribute, null, "Name", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, false);
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Attribute, null, "Weight" );
				tmpNode != null;
				tmpNode = getDomNextChild( Attribute, null, "Weight", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, false);
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://my.opera.com/VonPower/", "BasicFacet" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://my.opera.com/VonPower/", "BasicFacet", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new BasicFacetType(tmpNode).adjustPrefix();
		}
	}

	public static int getNameMinCount() {
		return 1;
	}

	public static int getNameMaxCount() {
		return 1;
	}

	public int getNameCount() {
		return getDomChildCount(Attribute, null, "Name");
	}

	public boolean hasName() {
		return hasDomChild(Attribute, null, "Name");
	}

	public SchemaString newName() {
		return new SchemaString();
	}

	public SchemaString getNameAt(int index) throws Exception {
		return new SchemaString(getDomNodeValue(dereference(getDomChildAt(Attribute, null, "Name", index))));
	}

	public org.w3c.dom.Node getStartingNameCursor() throws Exception {
		return getDomFirstChild(Attribute, null, "Name" );
	}

	public org.w3c.dom.Node getAdvancedNameCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Attribute, null, "Name", curNode );
	}

	public SchemaString getNameValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.altova.xml.XmlException("Out of range");
		else
			return new SchemaString(getDomNodeValue( dereference(curNode) ) );
	}

	public SchemaString getName() throws Exception 
 {
		return getNameAt(0);
	}

	public void removeNameAt(int index) {
		removeDomChildAt(Attribute, null, "Name", index);
	}

	public void removeName() {
		while (hasName())
			removeNameAt(0);
	}

	public void addName(SchemaString value) {
		if( value.isNull() == false )
		{
			appendDomChild(Attribute, null, "Name", value.toString());
		}
	}

	public void addName(String value) throws Exception {
		addName(new SchemaString(value));
	}

	public void insertNameAt(SchemaString value, int index) {
		insertDomChildAt(Attribute, null, "Name", index, value.toString());
	}

	public void insertNameAt(String value, int index) throws Exception {
		insertNameAt(new SchemaString(value), index);
	}

	public void replaceNameAt(SchemaString value, int index) {
		replaceDomChildAt(Attribute, null, "Name", index, value.toString());
	}

	public void replaceNameAt(String value, int index) throws Exception {
		replaceNameAt(new SchemaString(value), index);
	}

	public static int getWeightMinCount() {
		return 1;
	}

	public static int getWeightMaxCount() {
		return 1;
	}

	public int getWeightCount() {
		return getDomChildCount(Attribute, null, "Weight");
	}

	public boolean hasWeight() {
		return hasDomChild(Attribute, null, "Weight");
	}

	public SchemaDouble newWeight() {
		return new SchemaDouble();
	}

	public SchemaDouble getWeightAt(int index) throws Exception {
		return new SchemaDouble(getDomNodeValue(dereference(getDomChildAt(Attribute, null, "Weight", index))));
	}

	public org.w3c.dom.Node getStartingWeightCursor() throws Exception {
		return getDomFirstChild(Attribute, null, "Weight" );
	}

	public org.w3c.dom.Node getAdvancedWeightCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Attribute, null, "Weight", curNode );
	}

	public SchemaDouble getWeightValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.altova.xml.XmlException("Out of range");
		else
			return new SchemaDouble(getDomNodeValue( dereference(curNode) ) );
	}

	public SchemaDouble getWeight() throws Exception 
 {
		return getWeightAt(0);
	}

	public void removeWeightAt(int index) {
		removeDomChildAt(Attribute, null, "Weight", index);
	}

	public void removeWeight() {
		while (hasWeight())
			removeWeightAt(0);
	}

	public void addWeight(SchemaDouble value) {
		if( value.isNull() == false )
		{
			appendDomChild(Attribute, null, "Weight", value.toString());
		}
	}

	public void addWeight(String value) throws Exception {
		addWeight(new SchemaDouble(value));
	}

	public void insertWeightAt(SchemaDouble value, int index) {
		insertDomChildAt(Attribute, null, "Weight", index, value.toString());
	}

	public void insertWeightAt(String value, int index) throws Exception {
		insertWeightAt(new SchemaDouble(value), index);
	}

	public void replaceWeightAt(SchemaDouble value, int index) {
		replaceDomChildAt(Attribute, null, "Weight", index, value.toString());
	}

	public void replaceWeightAt(String value, int index) throws Exception {
		replaceWeightAt(new SchemaDouble(value), index);
	}

	public static int getBasicFacetMinCount() {
		return 1;
	}

	public static int getBasicFacetMaxCount() {
		return 1;
	}

	public int getBasicFacetCount() {
		return getDomChildCount(Element, "http://my.opera.com/VonPower/", "BasicFacet");
	}

	public boolean hasBasicFacet() {
		return hasDomChild(Element, "http://my.opera.com/VonPower/", "BasicFacet");
	}

	public BasicFacetType newBasicFacet() {
		return new BasicFacetType(domNode.getOwnerDocument().createElementNS("http://my.opera.com/VonPower/", "BasicFacet"));
	}

	public BasicFacetType getBasicFacetAt(int index) throws Exception {
		return new BasicFacetType(dereference(getDomChildAt(Element, "http://my.opera.com/VonPower/", "BasicFacet", index)));
	}

	public org.w3c.dom.Node getStartingBasicFacetCursor() throws Exception {
		return getDomFirstChild(Element, "http://my.opera.com/VonPower/", "BasicFacet" );
	}

	public org.w3c.dom.Node getAdvancedBasicFacetCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://my.opera.com/VonPower/", "BasicFacet", curNode );
	}

	public BasicFacetType getBasicFacetValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.altova.xml.XmlException("Out of range");
		else
			return new BasicFacetType( dereference(curNode) );
	}

	public BasicFacetType getBasicFacet() throws Exception 
 {
		return getBasicFacetAt(0);
	}

	public void removeBasicFacetAt(int index) {
		removeDomChildAt(Element, "http://my.opera.com/VonPower/", "BasicFacet", index);
	}

	public void removeBasicFacet() {
		while (hasBasicFacet())
			removeBasicFacetAt(0);
	}

	public void addBasicFacet(BasicFacetType value) {
		appendDomElement("http://my.opera.com/VonPower/", "BasicFacet", value);	
	}

	public void insertBasicFacetAt(BasicFacetType value, int index) {
		insertDomElementAt("http://my.opera.com/VonPower/", "BasicFacet", index, value);
	}

	public void replaceBasicFacetAt(BasicFacetType value, int index) {
		replaceDomElementAt("http://my.opera.com/VonPower/", "BasicFacet", index, value);
	}

	private org.w3c.dom.Node dereference(org.w3c.dom.Node node) {
		return node;
	}
}
