/**
 * FFTTest.java
 *
 * This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.FFTTest;


public class FFTTest {
	protected static void example() throws Exception {
		////////////////////////////////////////////////////////////////////
		//
		// TODO:
		//   Insert your code here...
		//
		// Example code to create and save a structure:
		//   FFTDoc doc = new FFTDoc();
		//   FFTableType root = new FFTableType(doc, "http://my.opera.com/VonPower/", "", "FFTable");
		//   doc.setSchemaLocation("FFT.xsd"); // optional
		//   ...
		//   doc.save("FFT1.xml", root);
		//
		// Example code to load and save a structure:
		//   FFTDoc doc = new FFTDoc();
		//   FFTableType root = new FFTableType(doc.load("FFT1.xml"));
		//   ...
		//   doc.save("FFT1.xml", root);
		//
		////////////////////////////////////////////////////////////////////
	}

	public static void main(String args[]) {
		try {
			System.out.println("FFT Test Application");
			example();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
}
