/**
 * dataFormulaTest.java
 *
 * This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.dataFormulaTest;


public class dataFormulaTest {
	protected static void example() throws Exception {
		////////////////////////////////////////////////////////////////////
		//
		// TODO:
		//   Insert your code here...
		//
		// Example code to create and save a structure:
		//   dataFormulaDoc doc = new dataFormulaDoc();
		//   DataFormulaType root = new DataFormulaType(doc, "", "", "DataFormula");
		//   doc.setSchemaLocation("dataFormula.xsd"); // optional
		//   ...
		//   doc.save("dataFormula1.xml", root);
		//
		// Example code to load and save a structure:
		//   dataFormulaDoc doc = new dataFormulaDoc();
		//   DataFormulaType root = new DataFormulaType(doc.load("dataFormula1.xml"));
		//   ...
		//   doc.save("dataFormula1.xml", root);
		//
		////////////////////////////////////////////////////////////////////
	}

	public static void main(String args[]) {
		try {
			System.out.println("dataFormula Test Application");
			example();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
}
